<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lots = [
            [
                'title' => '2014 Rossignol District Snowboard',
                'description' => 'Сноуборд Rossignol District Amptek - это удобная доска для фристайла для начинающих паркеров и пайп-райдеров. Автоматический разворот Amptek от Rossignol в сочетании с небольшим развалом обеспечивает плавную, но стабильную езду. Более мягкий симметричный изгиб делает District легкой в управлении доской, которая игрива и дает вам уверенность в совершенствовании своих навыков.',
                'url' => 'img/lots/lot-1.jpg',
                'price' => 10999,
                'bet_step' => 100,
                'author_id' => 1,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'DC Ply Mens 2016/2017 Snowboard',
                'description' => 'Настоящий зимний скейтборд на ваших ногах. Не обремененная весом, отлично спроектированная конструкция, которая проверена годами. Прогиб Lock & Load Camber с классическим кэмбером по середине для устойчивости и отличного щелчка! В этом году размерную линейку доски расширили, добавив пару вайдовых ростовок, чтобы райдеры с большим размером ноги тоже могли получить удовольствие от катания на этой потрясающей доске.',
                'url' => 'img/lots/lot-2.jpg',
                'price' => 159999,
                'bet_step' => 800,
                'author_id' => 2,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления Union Contact Pro 2015 года размер L/XL',
                'description' => 'Превратите всю гору в парк с привязкой Union go-to Freestyle. Contact Pro известен своей мягкой и удобной для серфинга опорной плитой с мини-диском, ультратонкими высокими спинками ASYM S2 Team и супер удобными ремешками Forma Elite на щиколотках. Путешествуйте по горам, катайтесь по парку и настраивайте в соответствии с желаниями вашего сердца, Contact Pro будет держать вас в напряжении весь сезон.',
                'url' => 'img/lots/lot-3.jpg',
                'price' => 8000,
                'bet_step' => 100,
                'author_id' => 3,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Ботинки для сноуборда DC Mutiny Charocal',
                'description' => 'Принимая во внимание стиль и быстрое комфортное надевание ботинок Mutiny, можно сказать, что эта модель — скейтовая обувь для сноубордиста. Простота традиционной шнуровки и плотная фиксация пятки за счет внутренней утяжки делают эти ботинки очевидным выбором для любого поклонника фристайла.',
                'url' => 'img/lots/lot-4.jpg',
                'price' => 10999,
                'bet_step' => 200,
                'author_id' => 4,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Куртка для сноуборда DC Amo 13 Blue Jay',
                'description' => 'Ветру не добраться до тела благодаря швам, проклеенным в критических мечтах. Глубокий расширяющийся капюшон можно носить со шлемом. Обилие карманов, в том числе внутренних для маски и плеера, позволяет держать все нужное при себе, не обременяя себя рюкзаком.',
                'url' => 'img/lots/lot-5.jpg',
                'price' => 7500,
                'bet_step' => 100,
                'author_id' => 1,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Маска Oakley Canopy',
                'description' => 'Маска Oakley дает стопроцентную защиту от лишних солнечных лучей, противостоит ударам, не запотевает, позволяет при необходимости быстро сменить линзу.',
                'url' => 'img/lots/lot-6.jpg',
                'price' => 5400,
                'bet_step' => 200,
                'author_id' => 2,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд CAPITA Ultrafear',
                'description' => 'Сноуборд Capita Ultrafear — хит бренда, завоевавший множество наград от самых известных тестов. Эта модель станет идеальным вариантом для фристайла и подойдет продвинутым райдерам.',
                'url' => 'img/lots/lot-7.jpg',
                'price' => 81999,
                'bet_step' => 500,
                'author_id' => 3,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд Burton Hideaway',
                'description' => 'Универсальный сноуборд Burton Hideaway станет отличным выбором для начинающих райдеров.',
                'url' => 'img/lots/lot-8.jpg',
                'price' => 68000,
                'bet_step' => 400,
                'author_id' => 4,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд Termit Chance',
                'description' => 'Termit Chance — идеальный сноуборд для начинающих.',
                'url' => 'img/lots/lot-9.jpg',
                'price' => 14999,
                'bet_step' => 100,
                'author_id' => 1,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд CAPITA Outerspace Living',
                'description' => 'Универсальная доска Outerspace Living от Capita — удачное сочетание динамичности и стабильности. Модель подойдет продвинутым сноубордистам.',
                'url' => 'img/lots/lot-10.jpg',
                'price' => 72999,
                'bet_step' => 300,
                'author_id' => 2,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд женский Termit Amica',
                'description' => 'Сноуборд Termit Amica создан для девушек, не привыкших скучать на склоне. Отзывчивый и маневренный, он заряжает хорошим настроением и поддерживает в желании прогрессировать.',
                'url' => 'img/lots/lot-11.jpg',
                'price' => 25000,
                'bet_step' => 300,
                'author_id' => 3,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд женский Termit Aura',
                'description' => 'Универсальная доска Termit Aura для прогрессирующих сноубордисток. Яркий дизайн не оставит вас незамеченной на склоне.',
                'url' => 'img/lots/lot-12.jpg',
                'price' => 25000,
                'bet_step' => 200,
                'author_id' => 4,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд детский Burton Riglet',
                'description' => 'Сноуборд Burton для самых маленьких позволит изучать базовые движения даже дома или во дворе.',
                'url' => 'img/lots/lot-13.jpg',
                'price' => 15999,
                'bet_step' => 100,
                'author_id' => 1,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд детский Termit Jockey',
                'description' => 'Детский сноуборд для начинающих покорителей склонов, который стал еще легче и мягче в этом сезоне. Простая и надежная конструкция, яркий дизайн — все, что нужно для начала занятий сноубордингом.',
                'url' => 'img/lots/lot-14.jpg',
                'price' => 13999,
                'bet_step' => 100,
                'author_id' => 2,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд Head Architect',
                'description' => 'Детский сноуборд для начинающих покорителей склонов, который стал еще легче и мягче в этом сезоне. Простая и надежная конструкция, яркий дизайн — все, что нужно для начала занятий сноубордингом.',
                'url' => 'img/lots/lot-15.jpg',
                'price' => 53999,
                'bet_step' => 300,
                'author_id' => 3,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд CAPITA The Outsiders',
                'description' => 'Сноуборд The Outsiders от Capita — отличный выбор для фристайла. Доска гарантирует уверенность на любом рельефе: будь то парковое катание, утренний вельвет или разбитая трасса. Модель подойдет для продвинутых райдеров.',
                'url' => 'img/lots/lot-16.jpg',
                'price' => 93999,
                'bet_step' => 500,
                'author_id' => 4,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд CAPITA The Outsiders',
                'description' => 'Сноуборд The Outsiders от Capita — отличный выбор для фристайла. Доска гарантирует уверенность на любом рельефе: будь то парковое катание, утренний вельвет или разбитая трасса. Модель подойдет для продвинутых райдеров.',
                'url' => 'img/lots/lot-17.jpg',
                'price' => 93999,
                'bet_step' => 500,
                'author_id' => 2,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноуборд Burton CUSTOM X',
                'description' => 'Агрессивный сноуборд Burton — отличный выбор для тех, кто ищет скорость и контроль Pro-уровня.',
                'url' => 'img/lots/lot-18.jpg',
                'price' => 116999,
                'bet_step' => 900,
                'author_id' => 1,
                'category_id' => 1,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические Termit Stream',
                'description' => 'Крепления, в которых собрано все самое лучшее. Легкая и прочная цельная база. Демпфирующие накладки на базу и хайбек для снижения ударных нагрузок при приземлениях. Широкий и мягкий кэп-стреп для улучшения фиксации и снижения давления на нос ботинка.',
                'url' => 'img/lots/lot-19.jpg',
                'price' => 14999,
                'bet_step' => 100,
                'author_id' => 2,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические Termit Aspire',
                'description' => 'Универсальные крепления Aspire подойдут прогрессирующим райдерам. Конструкция без пяточной дуги, полимерные эргономичные клипсы и хайбек с накладкой из ЭВА помогут постигать азы сноубординга с комфортом.',
                'url' => 'img/lots/lot-20.jpg',
                'price' => 8999,
                'bet_step' => 50,
                'author_id' => 3,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические женские Salomon Rhythm Lavender',
                'description' => 'Технологичные крепления Salomon Rhythm обеспечивают плотное прилегание, отзывчивость и прочность. Гибкая модель прощает ошибки и помогает повысить уровень катания, обеспечивая поддержку на любом уровне и в любых условиях.',
                'url' => 'img/lots/lot-21.jpg',
                'price' => 22999,
                'bet_step' => 300,
                'author_id' => 4,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические Burton Cartel X',
                'description' => 'Крепления Burton Cartel X — более жесткая версия легендарного крепления Cartel, которая подойдет для райдеров с профессиональным уровнем катания.',
                'url' => 'img/lots/lot-22.jpg',
                'price' => 51999,
                'bet_step' => 400,
                'author_id' => 1,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические Burton Freestyle',
                'description' => 'Еще больше возможностей на склоне с креплениями Burton Freestyle! Модель подойдет для начинающих райдеров.',
                'url' => 'img/lots/lot-23.jpg',
                'price' => 28999,
                'bet_step' => 300,
                'author_id' => 2,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические женские UNION Rosa',
                'description' => 'Мягкие женские крепления Union Rosa с высокой отзывчивостью прощают ошибки. Вам будет легко покорять свои первые спуски.',
                'url' => 'img/lots/lot-24.jpg',
                'price' => 23999,
                'bet_step' => 200,
                'author_id' => 3,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Крепления сноубордические детские Head P Jr',
                'description' => 'Детские сноубордические крепления начального уровня P Jr от Head.',
                'url' => 'img/lots/lot-25.jpg',
                'price' => 13999,
                'bet_step' => 100,
                'author_id' => 4,
                'category_id' => 2,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноубордические ботинки Termit Symbol',
                'description' => 'Универсальные ботинки Termit Symbol отлично подходят для любых условий. Ровные склоны, заснеженные поля или парк — эта модель справится со всем!',
                'url' => 'img/lots/lot-26.jpg',
                'price' => 13999,
                'bet_step' => 200,
                'author_id' => 1,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноубордические ботинки ThirtyTwo Lashed Double Boa 21',
                'description' => 'Сноубордические ботинки ThirtyTwo обеспечивают комфорт и отличную поддержку во время катания. Модель подойдет продвинутым райдерам.',
                'url' => 'img/lots/lot-27.jpg',
                'price' => 54999,
                'bet_step' => 400,
                'author_id' => 2,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноубордические ботинки женские ThirtyTwo Lashed Double Boa 21',
                'description' => 'Сноубордические ботинки ThirtyTwo обеспечивают комфорт и отличную поддержку во время катания. Модель подойдет продвинутым райдерам.',
                'url' => 'img/lots/lot-28.jpg',
                'price' => 58999,
                'bet_step' => 450,
                'author_id' => 3,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноубордические ботинки детские Head Velcro',
                'description' => 'Комфортные детские ботинки Head для первых шагов в сноубординге. Двойная стелька позволяет увеличить размер ботинка.',
                'url' => 'img/lots/lot-29.jpg',
                'price' => 12999,
                'bet_step' => 150,
                'author_id' => 4,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноубордические ботинки женские Termit Zephyr',
                'description' => 'Удобные и мягкие ботинки для начинающих сноубордисток. Модель подойдет к любому женскому сноуборду Termit.',
                'url' => 'img/lots/lot-30.jpg',
                'price' => 13999,
                'bet_step' => 150,
                'author_id' => 1,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => 'Сноубордические ботинки ThirtyTwo TM-2 Double Boa 21',
                'description' => 'Универсальные ботинки для сноубордистов с высоким уровнем катания. Удобная модель с облегченной подошвой для максимально комфортного катания.',
                'url' => 'img/lots/lot-31.jpg',
                'price' => 62999,
                'bet_step' => 450,
                'author_id' => 2,
                'category_id' => 3,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка утепленная мужская O'Neill Texture",
                'description' => 'Технологичная куртка O`Neill, специально разработанная для сноубордистов.',
                'url' => 'img/lots/lot-32.jpg',
                'price' => 9799,
                'bet_step' => 50,
                'author_id' => 3,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка утепленная мужская Termit",
                'description' => 'Куртка для сноубординга от Termit создана с использованием современных технологий и гарантирует максимальный комфорт на трассе.',
                'url' => 'img/lots/lot-33.jpg',
                'price' => 19499,
                'bet_step' => 150,
                'author_id' => 4,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка утепленная мужская DC Shoes Haven",
                'description' => 'Утепленная куртка DC Haven отлично подойдет для катания на сноуборде.',
                'url' => 'img/lots/lot-34.jpg',
                'price' => 32499,
                'bet_step' => 300,
                'author_id' => 1,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка-анорак мужская Protest",
                'description' => 'Анорак Protest Juicens, выполненный из мембранной ткани, сделает твой день на склоне максимально комфортным.',
                'url' => 'img/lots/lot-35.jpg',
                'price' => 21499,
                'bet_step' => 200,
                'author_id' => 2,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Анорак мужской DC Shoes DC-43",
                'description' => 'Сноубордический анорак DC-43 для комфорта на протяжении целого дня на склоне.',
                'url' => 'img/lots/lot-36.jpg',
                'price' => 20799,
                'bet_step' => 200,
                'author_id' => 3,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка утепленная мужская Protest",
                'description' => 'Отличным дополнением сноубордической экипировки станет технологичная и функциональная куртка Protest. Эффектный дизайн с камуфляжным принтом поможет выделиться на склоне.',
                'url' => 'img/lots/lot-37.jpg',
                'price' => 20799,
                'bet_step' => 200,
                'author_id' => 4,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка утепленная мужская Termit",
                'description' => 'Теплая водонепроницаемая куртка для катания на сноуборде от Termit станет незаменимой вещью в экипировке.',
                'url' => 'img/lots/lot-38.jpg',
                'price' => 19499,
                'bet_step' => 150,
                'author_id' => 1,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Куртка утепленная мужская DC Shoes Spectrum",
                'description' => 'Легкая куртка DC Spectrum создана для катания на сноуборде.',
                'url' => 'img/lots/lot-39.jpg',
                'price' => 19499,
                'bet_step' => 150,
                'author_id' => 2,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Джемпер флисовый мужской DC Shoes Bruiser",
                'description' => 'Удобный и практичный флисовый джемпер DC Bruiser — отличный утепляющий слой экипировки для зимних видов спорта.',
                'url' => 'img/lots/lot-40.jpg',
                'price' => 11699,
                'bet_step' => 100,
                'author_id' => 3,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Джемпер флисовый мужской Protest Barati",
                'description' => 'Флисовый джемпер Protest — незаменимая часть сноубордической экипировки. ',
                'url' => 'img/lots/lot-41.jpg',
                'price' => 4249,
                'bet_step' => 50,
                'author_id' => 1,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Джемпер флисовый мужской Quiksilver Powder Chaser",
                'description' => 'Джемпер Quiksilver — идеальный выбор для катания на сноуборде.',
                'url' => 'img/lots/lot-42.jpg',
                'price' => 9199,
                'bet_step' => 80,
                'author_id' => 2,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Брюки утепленные мужские DC Shoes Squadron",
                'description' => 'Технологичные брюки DC Squadron для катания на сноуборде.',
                'url' => 'img/lots/lot-43.jpg',
                'price' => 38999,
                'bet_step' => 300,
                'author_id' => 3,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Брюки утепленные мужские Protest",
                'description' => 'Утепленные сноубордические брюки Protest.',
                'url' => 'img/lots/lot-44.jpg',
                'price' => 12499,
                'bet_step' => 150,
                'author_id' => 4,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Брюки утепленные мужские DC Shoes Shadow Bib",
                'description' => 'Полукомбинезон DC Shadow Bib разработан для катания на сноуборде.',
                'url' => 'img/lots/lot-45.jpg',
                'price' => 12399,
                'bet_step' => 150,
                'author_id' => 1,
                'category_id' => 4,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Тиски для фиксации лыж и сноуборда HOLMENKOL Board / FreerideFix",
                'description' => 'Специальные тиски для сноубордов и широких лыж Board / FreerideFix от Holmenkol. Тиски обеспечивают быструю и легкую фиксацию лыж и досок в горизонтальном и вертикальном положении для обработки кантов и скользящей поверхности. Предусмотрено две позиции для обработки боковой стороны кантов: 90° и 60°.',
                'url' => 'img/lots/lot-46.jpg',
                'price' => 16999,
                'bet_step' => 200,
                'author_id' => 2,
                'category_id' => 5,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Бронзовая щетка Swix",
                'description' => 'Бронзовая щетка Swix средней жесткости. Используется для обработки скользящей поверхности после снятия парафина скребком.',
                'url' => 'img/lots/lot-47.jpg',
                'price' => 2999,
                'bet_step' => 30,
                'author_id' => 3,
                'category_id' => 5,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Смазочный утюг Swix T77",
                'description' => 'Экономичный смазочный утюг Economy от Swix. Предназначен для обработки как беговых и горных лыж, так и сноубордов. Эргономичный корпус и широкая нагревательная поверхность размером 100x160 мм. Обеспечивает температурный диапазон нагрева от 80 до 170 °С. Толстая металлическая подошва поддерживает стабильную температуру нагрева. Угловой скос с одной стороны для более легкого и точного ведения утюга с постоянной скоростью при обработке мазей скольжения. Мощность 1000 Вт.',
                'url' => 'img/lots/lot-48.jpg',
                'price' => 6099,
                'bet_step' => 50,
                'author_id' => 4,
                'category_id' => 5,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Пробка для подготовки лыж Nordway",
                'description' => 'Качественная пробка Nordway для обработки скользящей поверхности беговых лыж. Натуральная пробка позволяет равномерно нанести и растереть лыжную мазь по скользящей поверхности лыж. Также изделие предназначено для полировки блоков и фторуглеродных порошков холодным способом, разравнивания твердых мазей держания. Пробка Nordway подойдет как опытным спортсменам, так и любителям. ',
                'url' => 'img/lots/lot-49.jpg',
                'price' => 429,
                'bet_step' => 20,
                'author_id' => 1,
                'category_id' => 5,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Шлем Uvex Instinct Visor Pro V",
                'description' => 'Крутой, прогрессивный и стильный спортивный шлем all-mountain от Uvex с удобной посадкой и визором, автоматически меняющим трансмиссию в зависимости от освещения в диапазоне S1-S2. Шлем можно надевать поверх очков, корректирующих зрение. Магнитная бакля Fidlock позволяет быстро застегивать и расстегивать шлем одной рукой. Съемная подкладка шлема из гипоаллергенной дышащей ткани Coolmax быстро отводит влагу.',
                'url' => 'img/lots/lot-50.jpg',
                'price' => 53999,
                'bet_step' => 500,
                'author_id' => 2,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Шлем Uvex Wanted",
                'description' => 'Шлем Uvex с глубокой посадкой. Зеркальный визор категории S2 с показателем светопропускания 19–43% подходит для катания в условиях умеренной солнечной активности.',
                'url' => 'img/lots/lot-51.jpg',
                'price' => 28999,
                'bet_step' => 400,
                'author_id' => 3,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Шлем женский Glissade Crystal",
                'description' => 'Женский шлем Glisasde Crystal — необходимая деталь вашей горнолыжной экипировки. Внешняя композитная раковина Inmold, съемные ушные раковины и подшлемник обеспечивают максимальную безопасность и удобство. Фиксатор ремешка маски и система регулировки размера обеспечивают идеальную посадку. Шлем сочетается по дизайну с маской Glissade Riddle.',
                'url' => 'img/lots/lot-52.jpg',
                'price' => 7999,
                'bet_step' => 100,
                'author_id' => 4,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Маска Glissade Pilot",
                'description' => 'Базовая горнолыжная маска подойдет для катания в облачную погоду или при искусственном освещении.',
                'url' => 'img/lots/lot-53.jpg',
                'price' => 1699,
                'bet_step' => 50,
                'author_id' => 1,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Маска со сменной линзой Anon M3 W/SPR",
                'description' => 'Маска со сменной линзой Anon M3 W/SPR подойдет для катания в солнечную погоду.',
                'url' => 'img/lots/lot-54.jpg',
                'price' => 38999,
                'bet_step' => 400,
                'author_id' => 2,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Сумка Dakine BOOT LOCKER DLX, 70 л",
                'description' => 'Функциональная сумка для экипировки Boot Locker DLX позволит захватить на склон все необходимое. Модель выполнена из прочной ткани с водоотталкивающей пропиткой. Вместительное основное отделение на молнии имеет удобный доступ. Нижнее водонепроницаемое отделение на молнии предназначено для хранения мокрой экипировки. Для ботинок предусмотрено отделение на молнии, выполненное из плотной ткани, которая защищает остальные вещи. Очки и шлем отлично помещаются в специальный карман. Сумка имеет съемную лямку для более удобной переноски. Объем 70 л.',
                'url' => 'img/lots/lot-55.jpg',
                'price' => 11199,
                'bet_step' => 200,
                'author_id' => 3,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
            [
                'title' => "Чехол для сноуборда Dakine FREESTYLE, 157 см",
                'description' => 'Чехол с тонкими стенками от Dakine подойдет для перевозки сноубордов. Дно усилено армированным полиэтиленом. Молния почти по всему периметру позволяет легко и быстро достать экипировку. Для удобства переноски предусмотрена ручка и отстегивающийся плечевой ремень.',
                'url' => 'img/lots/lot-56.jpg',
                'price' => 12999,
                'bet_step' => 150,
                'author_id' => 4,
                'category_id' => 6,
                'creation_date' => Carbon::now()->timezone('Europe/Moscow'),
                'end_date' => Carbon::now()->addSeconds(604800)->timezone('Europe/Moscow'),
            ],
        ];
        DB::table('lots')->insert($lots);
    }
}
